import Foundation

@objc(AssistantServiceProtocol)
public protocol AssistantServiceProtocol {
    func ping(reply: @escaping (String) -> Void)
    func getTodayPlan(reply: @escaping (Data) -> Void)
    func submitPrompt(_ requestData: Data, reply: @escaping (Data) -> Void)
    func setGoogleRefreshToken(_ token: String, reply: @escaping (Bool) -> Void)
    func getMostRecentSessionId(reply: @escaping (String?) -> Void)
    func getMessages(sessionId: String, reply: @escaping (Data) -> Void)
    func registerEventClient(_ endpoint: NSXPCListenerEndpoint, reply: @escaping (Bool) -> Void)
    func computeGrade(courseId: String, projectionJSON: Data?, reply: @escaping (Data) -> Void)
    func enterGrade(itemId: String, earnedPoints: Double, reply: @escaping (Bool) -> Void)
    func listCourses(reply: @escaping (Data) -> Void)
    func upsertCourse(_ data: Data, reply: @escaping (Bool) -> Void)
    func listGradeData(courseId: String, reply: @escaping (Data) -> Void)
    func upsertCategory(_ data: Data, reply: @escaping (Bool) -> Void)
    func upsertItem(_ data: Data, reply: @escaping (Bool) -> Void)
    func deleteCategory(id: String, reply: @escaping (Bool) -> Void)
    func deleteItem(id: String, reply: @escaping (Bool) -> Void)
    func deleteCourse(id: String, reply: @escaping (Bool) -> Void)
    func setProviderAPIKey(provider: String, key: String, reply: @escaping (Bool) -> Void)
    func getProviderConfigured(provider: String, reply: @escaping (Bool) -> Void)
    func getSettings(reply: @escaping (Data) -> Void)
    func setSettings(_ data: Data, reply: @escaping (Bool) -> Void)
    func clearGoogleRefreshToken(reply: @escaping (Bool) -> Void)
}
