import Foundation

@objc(AssistantServiceProtocol)
public protocol AssistantServiceProtocol {
    func ping(reply: @escaping (String) -> Void)
    func getTodayPlan(reply: @escaping (Data) -> Void)
    func submitPrompt(_ requestData: Data, reply: @escaping (Data) -> Void)
    func setGoogleRefreshToken(_ token: String, reply: @escaping (Bool) -> Void)
    func getMostRecentSessionId(reply: @escaping (String?) -> Void)
    func getMessages(sessionId: String, reply: @escaping (Data) -> Void)
    func registerEventClient(_ endpoint: NSXPCListenerEndpoint, reply: @escaping (Bool) -> Void)
    func computeGrade(courseId: String, projectionJSON: Data?, reply: @escaping (Data) -> Void)
    func enterGrade(itemId: String, earnedPoints: Double, reply: @escaping (Bool) -> Void)
    func listCourses(reply: @escaping (Data) -> Void)
    func upsertCourse(_ data: Data, reply: @escaping (Bool) -> Void)
    func listGradeData(courseId: String, reply: @escaping (Data) -> Void)
    func upsertCategory(_ data: Data, reply: @escaping (Bool) -> Void)
    func upsertItem(_ data: Data, reply: @escaping (Bool) -> Void)
    func deleteCategory(id: String, reply: @escaping (Bool) -> Void)
    func deleteItem(id: String, reply: @escaping (Bool) -> Void)
    func deleteCourse(id: String, reply: @escaping (Bool) -> Void)
    func setProviderAPIKey(provider: String, key: String, reply: @escaping (Bool) -> Void)
    func getProviderConfigured(provider: String, reply: @escaping (Bool) -> Void)
    func getSettings(reply: @escaping (Data) -> Void)
    func setSettings(_ data: Data, reply: @escaping (Bool) -> Void)
    func clearGoogleRefreshToken(reply: @escaping (Bool) -> Void)
    func setGoogleClientSecret(_ secret: String, reply: @escaping (Bool) -> Void)
    func getGoogleClientSecret(reply: @escaping (String?) -> Void)
    func googleAccountTimeZone(reply: @escaping (String?) -> Void)
    func getDashboardSummary(reply: @escaping (Data) -> Void)
    func getWeekEvents(startISO: String, endISO: String, reply: @escaping (Data) -> Void)
    func createCalendarEvent(_ data: Data, reply: @escaping (Data) -> Void)
    func updateCalendarEvent(_ data: Data, reply: @escaping (Bool) -> Void)
    func deleteCalendarEvent(eventId: String, reply: @escaping (Bool) -> Void)
    func listCategories(reply: @escaping (Data) -> Void)
    func saveCategory(originalName: String?, name: String, colorHex: String,
                      reply: @escaping (Bool) -> Void)
    func removeCategory(name: String, reply: @escaping (Bool) -> Void)
    func setEventCategory(eventId: String, category: String,
                          reply: @escaping (Bool) -> Void)
    func getWeekTasks(startISO: String, endISO: String, reply: @escaping (Data) -> Void)
    func rescheduleTask(taskId: String, dueISO: String, reply: @escaping (Bool) -> Void)
    func completeTask(taskId: String, reply: @escaping (Bool) -> Void)
}
